[build]
    publish = "build"
    command = "npm run build"

[dev]
    command = "npm start"
    port = 3000

[functions]
    directory = "functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
        
